CREATE TABLE `patients` (
	`id` text NOT NULL,
	`owner` text NOT NULL,
	`name` text NOT NULL,
	`social_name` text,
	`dob` text,
	`cpf` text,
	`rg` text,
	`gender` text,
	`occupation` text,
	`marital_status` text,
	`schooling` text,
	`nationality` text,
	`phone` text,
	`secondary_phone` text,
	`email` text,
	`preferred_contact` text,
	`zip_code` text,
	`street` text,
	`address_number` text,
	`complement` text,
	`neighborhood` text,
	`city` text,
	`state` text,
	`guardian_name` text,
	`guardian_relationship` text,
	`guardian_phone` text,
	`emergency_name` text,
	`emergency_relationship` text,
	`emergency_phone` text,
	`insurance` text,
	`insurance_number` text,
	`referral_source` text,
	`admin_notes` text,
	`search_text` text NOT NULL,
	`version` integer DEFAULT 1 NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	PRIMARY KEY(`owner`, `id`)
);
--> statement-breakpoint
CREATE UNIQUE INDEX `patients_owner_cpf` ON `patients` (`owner`,`cpf`);--> statement-breakpoint
CREATE INDEX `patients_owner_name` ON `patients` (`owner`,`name`);